### ISSUE TITLE
seems to be missing 5th tone

### ISSUE THREAD

**Issue by meisei4** [maltevonehren/pinyin-numbers-to-tone-marks#2]
I'm not sure if its a bug, but this seems to be missing the 5th/neutral tone I believe? 
https://en.wikipedia.org/wiki/Standard_Chinese_phonology#Neutral_tone

Here's a deck that uses neutral tone https://ankiweb.net/shared/info/1864427328

<img width="396" alt="image" src="https://github.com/user-attachments/assets/8544d19d-7acc-4745-9c1e-55d58db9a8f9">

it just results in "5"

**Comment by maltevonehren** [comment]
I updated the add on to add support for this. Anki should automatically ask you to update and then it should work after a restart

**Comment by meisei4** [comment]
looks good! thank you!
<img width="425" alt="image" src="https://github.com/user-attachments/assets/0e845159-bed2-4f41-85ee-34ae63c3cffd" />
